// Data Produk Wanita - non-module global script
window.dataWanita = [
  // baju / top
  { id: "kaos-crew", nama: "T-Shirt Crew Neck", category: "bj",
    deskripsi: "T-shirt dengan potongan crew neck yang klasik dan nyaman. Terbuat dari bahan katun berkualitas tinggi yang lembut di kulit.",
    harga: "Rp199.000", priceNumeric: 199000,
    img: "https://riraclothing.com/wp-content/uploads/2024/11/Blouse.webp" },
  // celana
  { id: "celana-linen", nama: "Celana Linen Blend", category: "cl",
    deskripsi: "Celana dengan bahan linen blend yang breathable dan nyaman. Cocok untuk cuaca tropis dengan potongan yang flowy dan elegan.",
    harga: "Rp499.000", priceNumeric: 499000,
    img: "https://riraclothing.com/wp-content/uploads/2024/06/celana-wanita-santai.webp" },
  // rok
  { id: "rok-span", nama: "Rok Span Midi Hitam", category: "ro",
    deskripsi: "Rok pensil midi dengan belahan belakang untuk memudahkan gerakan. Bahan scuba yang tebal memberikan tampilan yang rapi dan profesional.",
    harga: "Rp180.000", priceNumeric: 180000,
    img: "https://6a783b1f51198decb75276c1.imgix.net/sandbox/Yeni%20%C3%9Cr%C3%BCnler.jpg?auto=compress" },
  { id: "rok-matches", nama: "Rok Midi Motif Matches", category: "ro",
    deskripsi: "Rok midi elegan dengan motif yang stylish dan modern, cocok untuk acara kasual maupun semi-formal.",
    harga: "Rp180.000", priceNumeric: 180000,
    img: "https://6a783b1f51198decb75276c1.imgix.net/sandbox/Matches.jpg" },
  // dress
  { id: "Evening_Gown", nama: "Burgundy Off-Shoulder Lace Dress", category: "dr",
    deskripsi: "Gaun mewah berbahan renda dengan potongan bahu terbuka (off-shoulder), memberikan kesan vintage sekaligus sensual.",
    harga: "Rp4.331.859", priceNumeric: 4331859,
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT9sEwB7Iw8XrEs8K87JqYy0phnvQNCLq9o87TmYOYqA7HwiAPuxjTxM0lWxim5JOD7yUpUmJcp5tikceRB9tFgkEb-6u2lxTP8B57xigSLfGMOepvUVbBw" },
  { id: "Overall_Dress", nama: "Gaun Overall Denim Pink", category: "dr",
    deskripsi: "Pilihan santai berupa overall denim berwarna merah muda, sangat pas untuk gaya casual remaja atau jalan-jalan siang hari.",
    harga: "Rp170.000", priceNumeric: 170000,
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTbzxso20wSxP6H8BiPXkeoMLV66xXaCYJHsfLu8YSF6ZAUCUCBy9G97P08Q2tls-fvfmY6Va7z7WpGeO4YjJ2uJfrAQbbCjQ" },
  { id: "Pleated_Midi", nama: "Ira Pleated Dress", category: "dr",
    deskripsi: "Gaun midi dengan detail lipit (pleated) dan motif marmer yang elegan, memberikan siluet yang mengalir ringan.",
    harga: "Rp2.381.659", priceNumeric: 2381659,
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT1jNm2TvClrFmiX_1iNz6pHD7wR_8cljC6FnM7zaGMQAOWX29SsgfaqOnJAr1MhygLnyzuDnzYEyXfy_if2gnsXczkhg3U" },
  { id: "Puff_Sleeve_Dress", nama: "Pomelo Puffed Sleeve Mini Dress", category: "dr",
    deskripsi: "Gaun dengan potongan A-Line yang klasik, dirancang untuk kenyamanan maksimal dengan bahan yang breathable.",
    harga: "Rp251.600", priceNumeric: 251600,
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaWFzfC-JwWm19yxbok0lwdfYZa_sXu4EA-oiqG1sGFOiNdpGjy3CykVAUuHflIab1YHzTvSQO3VI9Rx40ISW0FpVo9ApwR_RRqJWZUzmkBAGk4ectbIP3sw" },
  { id: "A_Line_Dress", nama: "Willow A Line Dress", category: "dr",
    deskripsi: "Dress A-line dengan siluet yang flattering dan bahan berkualitas tinggi. Cocok untuk berbagai acara formal maupun kasual.",
    harga: "Rp730.986", priceNumeric: 730986,
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQJRA3rZp4dAjgzNHhqbhN4ajdVVcE9od-9LnuPOl5UXK6iIvj1mK1_2vCKZ4hSrVsiitgsQf6BSeIIy6-b4YnHRUviKm1-K_8af6T6E1kInHfNzRLZqO-MXw" },
  { id: "maxi_dress", nama: "Sierra Sweetheart Maxi Dress", category: "dr",
    deskripsi: "Maxi dress dengan potongan sweetheart yang elegan. Bahan yang flowy memberikan kenyamanan sepanjang hari.",
    harga: "Rp499.000", priceNumeric: 499000,
    img: "https://balticborn.com/cdn/shop/products/sierra-sweetheart-maxi-dress-navy-806826.jpg?v=1762199048&width=600" },
  // outerwear
  { id: "jaket_parka", nama: "Jaket Parka Ringan Wanita", category: "op",
    deskripsi: "Jaket parka ringan yang cocok untuk cuaca dingin. Desain minimalis dengan fungsi maksimal.",
    harga: "Rp599.000", priceNumeric: 599000,
    img: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000" }
];
